name: check
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-check:
    name: Code Quality & Security
    runs-on: macos-latest # Required to correctly lint MacOS bridge files
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # Native Node 24 support
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6 # Native Node 24 support
        with:
          go-version: '1.25.4'
          cache: true

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

      - name: Run unit tests
        run: |
          go test -v ./...