name: CI

# 1. Explicitly set top-level permissions to "read-all" as a safety baseline
permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.25.4'
      - name: Test
        run: go test -tags locksmith_admin -v ./...

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.25.4'
      - name: Test
        run: go test -tags locksmith_admin -v ./...

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.25.4'
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev
      - name: Test
        run: go test -tags locksmith_admin -v ./...
